# Generated by Django 5.1.6 on 2025-02-26 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("auth0_id", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("order_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "shipment_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("tracking_number", models.CharField(max_length=50)),
                ("warehouse_id", models.CharField(max_length=20)),
                ("fulfillment_region", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                ("address_id", models.CharField(max_length=20)),
                ("fulfillment_type", models.CharField(max_length=20)),
                ("ship_date", models.DateField()),
                ("estimated_delivery", models.DateField()),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("current_status", models.CharField(max_length=50)),
                ("last_scan_location", models.CharField(max_length=100)),
                ("scan_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_attempt_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "delivery_failure_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="core.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.shipment",
                    ),
                ),
            ],
        ),
    ]
